name: pull-request-test
on: [pull_request]
jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
          OWNER: umipro-web-dev
          REPO: float-caluclator

        uses: actions/checkout@v4
      - name: installing node
        uses: action/setup-node@v4
        with: 
          node-version: 20.x

      - run: npm ci
      - run: TEST_RESULT=$(npm run test)
      - run: TEST_RESULT_CODE=$?
      - run: echo $TEST_RESULT
      - run: LINT_RESULT=$(npm run lint)
      - run: LINT_RESULT_CODE=$?
      - run: echo $LINT_RESULT
      - run: RESULTS_CODE=$(($TEST_RESULT_CODE+$TEST_RESULT_CODE))
      - run: |
          if [ $RESULTS_CODE = 0 ]; then
            gh api -X POST -f state="success" /repos/${OWNER}/${REPO}/statuses/${SHA}
          else
            gh api -X POST -f state="failure" /repos/${OWNER}/${REPO}/statuses/${SHA}
          fi
